### ISSUE TITLE
[INFO] Framework usando CSS Grid Layout

### ISSUE THREAD

**Issue by eliabejr** [simoneas02/awesome-grid-layout#2]
Simone! Graças ao seu artigo, construi a parte de automatização de CSS Grid Layouts do framework que estou construindo, chegamos até a nos falar no encontro Locaweb de Recife.

Segue link do repositório do framework:
https://github.com/EliabeJr/alpha-framework

PS: Ainda estou criando a documentação.

**Comment by simoneas02** [comment]
Oi @EliabeJr, tudo bem?

Na verdade os links a serem inclusos na lista awesome-grid-layout, são sobre como usar ou iniciar  com CSS Grid, no futuro posso abrir uma feature sobre aplicações em produção que usam CSS Grid, onde caberia adicionar o link da sua aplicação...

Caso queira adicionar novos links interessantes sobre CSS Grid é só seguir os passos relatados no [Guidelines to contribute](https://github.com/simoneas02/awesome-grid-layout/blob/master/contributing.md).

Abraços :)
